export default {
	actions: {
		SEARCH: 'SEARCH',
		CLEAR_SEARCH_RESULTS: 'CLEAR_SEARCH_RESULTS',
		RECEIVE_SEARCH_RESULTS: 'RECEIVE_SEARCH_RESULTS',
		UPDATE_CRITERIA: 'UPDATE_CRITERIA',
		CREATE_RECORD: 'CREATE_RECORD',
		RECEIVE_RECORD_ID: 'RECEIVE_RECORD_ID',
		REDIRECT_TO_RECORD: 'REDIRECT_TO_RECORD',
		SELECT_TEASER: 'SELECT_TEASER',
		FETCH_REPORT: 'FETCH_REPORT',
		RECEIVE_REPORT: 'RECEIVE_REPORT',
		LOGIN: 'LOGIN',
		RECEIVE_USER: 'RECEIVE_USER',
		LOGOUT: 'LOGOUT',
		GET_USAGE: 'GET_USAGE',
		RECEIVE_USAGE: 'RECEIVE_USAGE'
	},
	reportTypes: {
		PERSON: 'people',
		PHONE: 'phones',
		LOCATION: 'locations'
	}
};
