export default {
	actions: {
		SEARCH: 'SEARCH',
		RECEIVE_SEARCH_RESULTS: 'RECEIVE_SEARCH_RESULTS',
		UPDATE_CRITERIA: 'UPDATE_CRITERIA',
		ADD_RECORD: 'ADD_RECORD',
		RECEIVE_RECORD_ID: 'RECEIVE_RECORD_ID',
		CLEAR_NAVIGATION: 'CLEAR_NAVIGATION',
		FETCH_REPORT: 'FETCH_REPORT',
		RECEIVE_REPORT: 'RECEIVE_REPORT',
		LOGIN: 'LOGIN',
		RECEIVE_USER: 'RECEIVE_USER',
		LOGOUT: 'LOGOUT'
	},
	reportTypes: {
		PERSON: 'people',
		PHONE: 'phones',
		LOCATION: 'locations'
	}
};
